### ISSUE TITLE
Server Crashes using Command

### ISSUE THREAD

**Issue by Camawama** [Pxl-8/ColouredChat#3]
People on my server have started abusing a bug and crashing the server. If you type the command to set color but use a color not on the list it crashes the server.

**Comment by uberifix** [comment]
Alright this was a stupid oversight. 1.12 catches for this and throws an error but it seems I forgot to add this bit of code back in 1.14 and 1.15. Just pushed commits fixing this issue and releases on github are deploying now. Will upload to curseforge asap, thanks for the notice

**Comment by Camawama** [comment]
Thank you! that was without a doubt the quickest response and fix I have gotten from any Mod Dev!

**Comment by uberifix** [comment]
I like fixing my mods but people rarely ever open issues unfortunately, this was a serious issue that was an easy fix that's apparently existed since October lol

**Comment by Camawama** [comment]
Well, I love reaching out to help developers. I always report issues when I find them.

I am constantly making Modpacks with my friends and we ALWAYS find bugs!
